pipeline {
   agent any
   options { disableConcurrentBuilds() }
   stages {

    stage( 'build' ) {
      steps{
       }
    }
    
    stage( 'deploy' ) {
      steps{
      }
     }
  }
}
