pipeline {
   agent any
   options { disableConcurrentBuilds() }
   stages {

    stage( 'build' ) {
      steps{
            dockerNode(credentialsId: '', dockerHost: 'tcp://:2375', image: 'TerraSyncTarTest', remoteFs: '') {
                // some block
            }
       }
    }
  }
}
